# Site settings
title: Shobhit Jain Portfolio
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shobhit Jain
user_description: Portfolio
user_title: Python/C/C++
email: shobjain09@gmail.com
twitter_username: lorem_ipsum
github_username:  Shobhits7
gplus_username:  Shobhitjain

# Google-analytics
google-analytics:
  id: "G-L1HJ6GSDDD"

exclude: ['package.json', 'src' , 'node_modules']
